list(
    map(include('generate_parts'), key=regex('build_parts', ignore_case=True)),
    map(include('generate_csv'), key=regex('generate_csvs', ignore_case=True)),
    map(include('generate_crowd_anki'), key=regex('generate_crowd_anki', ignore_case=True))
)

---

generate_parts:
  list(
    map(include('from_parts'), key=regex('from_parts', ignore_case=True)),
    map(include('from_csv'), key=regex('from_csvs', ignore_case=True)),
    map(include('from_crowd_anki'), key=regex('from_crowd_anki', ignore_case=True))
  )



from_crowd_anki:
  folder: str()
  notes: include('from_ca_notes', required=False)
  note_models: list(include('from_ca_note_models'), required=False)
  headers: include('from_ca_headers', required=False)
  media: any(bool(), include('ca_media'), required=False)


generate_crowd_anki:
  folder: str()
  headers: str()
  notes: include('notes_to_source')
  note_models: include('note_models_to_source')
  media: any(bool(), include('ca_media'), required=False)



from_ca_notes:
  part_id: str()
  sort_order: list(str(), required=False)
  save_to_file: str(required=False)

from_ca_note_models:
  part_id: str()
  model_name: str(required=False)
  save_to_file: str(required=False)

from_ca_headers:
  part_id: str()
  save_to_file: str(required=False)

ca_media:
  from_notes: bool()
  from_note_models: bool()

note_models_to_source:
  parts: list(include('note_model_to_source'))

note_model_to_source:
  part: str()

notes_to_source:
  part: str()
  sort_order: list(str(), required=False)
  reverse_sort: bool(required=False)
  additional_items_to_add: map(str(), key=str(), required=False)




from_parts:
  notes: list(include('part_to_read'), required=False)
  note_models: list(include('part_to_read'), required=False)
  headers: list(include('part_to_read'), required=False)

part_to_read:
  part_id: str()
  file: str()



from_csv:
  notes:
    part_id: str()
    save_to_file: str(required=False)
    note_model_mappings: list(include('note_model_mapping'))
    file_mappings: list(include('file_mapping'))

generate_csv:
  notes: str()
  note_model_mappings: list(include('note_model_mapping'))
  file_mappings: list(include('file_mapping'))

note_model_mapping:
  note_models: list(str())
  columns_to_fields: map(str(), key=str())
  personal_fields: list(str())

file_mapping:
  file: str()
  note_model: str(required=False)
  sort_by_columns: list(str(), required=False)
  reverse_sort: bool(required=False)
  derivatives: list(include('file_mapping'), required=False)