list(
  map(include('build_parts'), key=regex('build_part[s]?', ignore_case=True)),
  map(any(include('generate_crowd_anki'), list(include('generate_crowd_anki'))), key=regex('generate_crowd_anki', ignore_case=True)),
  map(any(include('generate_csvs'), list(include('generate_csvs'))), key=regex('generate_csv[s]?', ignore_case=True))
)


---

build_parts:
    list(
      map(any(include('headers_from_crowd_anki'), list(include('headers_from_crowd_anki'))), key=regex('header[s]?_from_crowd_anki', ignore_case=True)),
      map(any(include('headers_from_yaml_part'), list(include('headers_from_yaml_part'))), key=regex('header[s]?_from_yaml_part', ignore_case=True)),
      map(any(include('media_group_from_crowd_anki'), list(include('media_group_from_crowd_anki'))), key=regex('media_group_from_crowd_anki', ignore_case=True)),
      map(any(include('media_group_from_folder'), list(include('media_group_from_folder'))), key=regex('media_group_from_folder', ignore_case=True)),
      map(any(include('media_group_from_yaml_part'), list(include('media_group_from_yaml_part'))), key=regex('media_group_from_yaml_part', ignore_case=True)),
      map(any(include('note_model_from_html_parts'), list(include('note_model_from_html_parts'))), key=regex('note_model_from_html_parts', ignore_case=True)),
      map(any(include('note_model_template_from_html'), list(include('note_model_template_from_html'))), key=regex('note_model_template[s]?_from_html', ignore_case=True)),
      map(any(include('note_models_from_crowd_anki'), list(include('note_models_from_crowd_anki'))), key=regex('note_model[s]?_from_crowd_anki', ignore_case=True)),
      map(any(include('note_models_from_yaml_part'), list(include('note_models_from_yaml_part'))), key=regex('note_model[s]?_from_yaml_part', ignore_case=True)),
      map(any(include('notes_from_crowd_anki'), list(include('notes_from_crowd_anki'))), key=regex('notes_from_crowd_anki', ignore_case=True)),
      map(any(include('notes_from_csvs'), list(include('notes_from_csvs'))), key=regex('notes_from_csv[s]?', ignore_case=True)),
      map(any(include('notes_from_yaml_part'), list(include('notes_from_yaml_part'))), key=regex('notes_from_yaml_part', ignore_case=True)),
      map(any(include('save_media_groups_to_folder'), list(include('save_media_groups_to_folder'))), key=regex('save_media_group[s]?_to_folder', ignore_case=True))
    )

generate_crowd_anki:
    folder: str()
    headers: str()
    notes: include('notes_to_crowd_anki')
    note_models: include('note_models_to_crowd_anki')
    media: include('media_group_to_crowd_anki', required=False)

generate_csvs:
    notes: str()
    note_model_mappings: list(include('note_model_mapping'))
    file_mappings: list(include('file_mapping'))


---

file_mapping:
    file: str()
    note_model: str(required=False)
    sort_by_columns: list(str(), required=False)
    reverse_sort: bool(required=False)
    derivatives: list(include('file_mapping'), required=False)

headers_from_crowd_anki:
    source: str()
    part_id: str()
    save_to_file: str(required=False)

headers_from_yaml_part:
    part_id: str()
    file: str()
    override: include('headers_override', required=False)

headers_override:
    deck_description_html_file: str(required=False)

media_group_from_crowd_anki:
    part_id: str()
    save_to_file: str(required=False)
    source: str()
    recursive: bool(required=False)
    filter_whitelist_from_parts: list(str(), required=False)
    filter_blacklist_from_parts: list(str(), required=False)

media_group_from_folder:
    part_id: str()
    save_to_file: str(required=False)
    source: str()
    recursive: bool(required=False)
    filter_whitelist_from_parts: list(str(), required=False)
    filter_blacklist_from_parts: list(str(), required=False)

media_group_from_yaml_part:
    part_id: str()
    file: str()

media_group_to_crowd_anki:
    parts: list(str())

note_model_field:
    name: str()
    font: str(required=False)
    font_size: int(required=False)
    is_sticky: bool(required=False)
    is_right_to_left: bool(required=False)

note_model_from_html_parts:
    part_id: str()
    model_id: str()
    css_file: str()
    fields: list(include('note_model_field'))
    templates: list(str())
    model_name: str(required=False)
    save_to_file: str(required=False)

note_model_mapping:
    note_models: any(list(str()), str())
    columns_to_fields: map(str(), key=str())
    personal_fields: list(str())

note_model_template_from_html:
    part_id: str()
    html_file: str()
    template_name: str(required=False)
    browser_html_file: str(required=False)
    deck_override_id: int(required=False)
    save_to_file: str(required=False)

note_models_from_crowd_anki:
    source: str()
    part_id: str()
    model_name: str(required=False)
    save_to_file: str(required=False)

note_models_from_yaml_part:
    part_id: str()
    file: str()

note_models_to_crowd_anki:
    parts: list(include('note_models_to_crowd_anki_item'))

note_models_to_crowd_anki_item:
    part_id: str()

notes_from_crowd_anki:
    source: str()
    part_id: str()
    sort_order: list(str(), required=False)
    save_to_file: str(required=False)
    reverse_sort: str(required=False)

notes_from_csvs:
    part_id: str()
    save_to_file: str(required=False)
    note_model_mappings: list(include('note_model_mapping'))
    file_mappings: list(include('file_mapping'))

notes_from_yaml_part:
    part_id: str()
    file: str()

notes_override:
    note_model: str(required=False)

notes_to_crowd_anki:
    part_id: str()
    sort_order: list(str(), required=False)
    reverse_sort: bool(required=False)
    additional_items_to_add: map(str(), key=str(), required=False)
    override: include('notes_override', required=False)

save_media_groups_to_folder:
    parts: list(str())
    folder: str()
    clear_folder: bool(required=False)
    recursive: bool(required=False)
