const sidebars = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Getting started',
      items: [
        'getting-started/install',
        'getting-started/quickstart',
        'getting-started/cli-tour',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'concepts/what-is-federation',
        'concepts/canonical-deck',
        'concepts/identity',
        'concepts/overlays',
        'concepts/media',
      ],
    },
    {
      type: 'category',
      label: 'Authoring',
      items: [
        'authoring/workspace',
        'authoring/manifests-targets',
        'authoring/translations',
        'authoring/extensions',
        'authoring/field-fills',
        'authoring/media',
        'authoring/importing-crowdanki',
        'authoring/crowdanki-bootstrap-boundary',
        'authoring/packages-locking',
        'authoring/verify-export',
        'authoring/diff-explain',
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      items: [
        'examples/ultimate-geography',
        'examples/hardcore-geography',
        'examples/downstream-package',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/glossary',
        'reference/yaml',
        'reference/cli',
        'reference/workbench',
        'reference/workspace-transactions',
        'reference/lockfile',
        'reference/release-oracle',
        'reference/crowdanki-equivalence-oracle',
        'reference/releasing',
        'reference/project-scope',
        {
          type: 'category',
          label: 'Architecture decisions',
          link: { type: 'doc', id: 'reference/decisions/README' },
          items: [{ type: 'autogenerated', dirName: 'reference/decisions' }],
        },
        {
          type: 'category',
          label: 'Research notes',
          items: ['reference/research/iced-and-anki-add-on'],
        },
      ],
    },
  ],
};

module.exports = sidebars;
