name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependecies
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: install -d

    - name: Enter pipenv
      run: pipenv shell

    - name: Run tests
      run: py.test

    - name: Build Yamale Recipe
      run: python scripts/yamale_build.py
