name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependecies
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: install -d

    - name: Run tests
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: run unit_tests

    - name: Build Yamale Recipe
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: run build_yamale

    - name: Check Yamale Recipe for changes
      run: git diff --quiet -- || (echo "::error file=yamale,line=0,col=0::You need to run 'python scripts/yamale_build.py'" && exit 1)

