name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pipenv
        pipenv install

    - name: Run tests
      run: |
        pipenv run unit_tests

    - name: Build Yamale Recipe
      run: |
        pipenv run build_yamale

    - name: Check Yamale Recipe for changes
      run: git diff --quiet -- || (echo "::error file=yamale,line=0,col=0::You need to run 'python scripts/yamale_build.py'" && exit 1)

